### ISSUE TITLE
Cuento termina al hacer clic en estante

### ISSUE THREAD

**Issue by jurelmetal** [Alejandra-canales1987/pagina_interactiva_JS#2]
El cuento termina aunque no haya ordenado los otros dos elementos, al hacer clic en el estante. Lo esperado es que el cuento no termine hasta que el usuario "ordene" los tres elementos.

**Comment by Alejandra-canales1987** [comment]
aqui me dejaste polla jajaja

**Comment by Alejandra-canales1987** [comment]
ya lo resolvimos =)
